services:
  node-server:
    container_name: node # ตั้งชื่อ container (เหมือน --name)
    build: . # ตำแหน่ง dockerfile
    ports:
      - "8000:8000" # map port ออกมา เหมือน -p ใน docker run  
    volumes:
      - ../client:/usr/src/app/client

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root # กำหนด user ของ root mysql
      MYSQL_DATABASE: tutorial # กำหนด database เริ่มต้นของ mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_test:/var/lib/mysql # map โฟลเดอร์ /data ในเครื่อง host ไปยัง /var/lib/mysql ใน container เพื่อเก็บข้อมูลของ mysql ไว้ใน host

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: php_myadmin
    environment:
      PMA_HOST: mysql_db # ระบุ host ที่จะให้ phpmyadmin ไปจัดการ ซึ่งสามารถใส่เป็นชื่อ container name (mysql_db) ได้เลย
      PMA_PORT: 3306 # ระบุ port ของ Database
      PMA_USER: root # ระบุ user ของ Database
      PMA_PASSWORD: root # ระบุ password ของ Database
    ports:
      - "8080:80"
    depends_on:
      - db # ระบุว่าต้องรอให้ container db สร้างเสร็จก่อนถึงจะสร้าง container phpmyadmin ได้

volumes:
  mysql_data_test: # กำหนดชื่อ volume ที่ต้องการจะสร้าง
    driver: local